AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: infospace-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    Handler: lambda_function.lambda_handler
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        TZ: Asia/Tokyo

Parameters:
  Stage:
    Type: String
    Default: dev

Conditions:
  IsProd: !Equals [!Ref Stage, "prod"]

Resources:

# ------------------------------------------------------------#
#  Lambda Function
# ------------------------------------------------------------#
  InfospaceCorporation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/infospace-corporation
      Policies:
        - AmazonDynamoDBFullAccess
      Description: ''
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref InfospaceLayer

# ------------------------------------------------------------#
#  Lambda Layer
# ------------------------------------------------------------#
  InfospaceLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: common functions
      ContentUri: ./src/layer
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: "Delete"
    Metadata:
      BuildMethod: python3.12
