AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: infospace-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    Handler: lambda_function.lambda_handler
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        TZ: Asia/Tokyo
  Api:
    OpenApiVersion: 3.0.2
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Stage, "prod"]

Resources:
  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Stage}-jwt-secret"
      Description: "JWT Secret Key for token generation and validation"
      GenerateSecretString:
        SecretStringTemplate: '{"JWT_SECRET_KEY":""}'
        GenerateStringKey: "JWT_SECRET_KEY"
        PasswordLength: 32
        ExcludeCharacters: '"@/\\'

  JwtSecretParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/weekly-report/${Stage}/jwt-secret-key"
      Type: String
      Value: !Sub "{{resolve:secretsmanager:${JwtSecret}:SecretString:JWT_SECRET_KEY}}"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  # ------------------------------------------------------------#
  #  Lambda Function
  # ------------------------------------------------------------#
  OrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-organization"
      CodeUri: ./src/Organization
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
                - ses:SendEmail
              Resource: "*"
      Description: ""
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Events:
        ProcOrganization:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /organization
            Method: ANY

  MemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-member"
      CodeUri: ./src/Member
      Policies:
        - AmazonDynamoDBFullAccess
      Description: ""
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer
      Events:
        ProcMember:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /member
            Method: ANY
        GetMemberProject:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /member/project
            Method: get

  WeeklyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-weekly-report"
      CodeUri: ./src/WeeklyReport
      Handler: lambda_function.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
                - ses:SendEmail
              Resource: "*"
      Description: "Weekly Report API Handler"
      Layers:
        - !Ref CommonLayer
      Events:
        ProcWeeklyReport:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /weekly-report
            Method: ANY
        GetReportStatus:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /weekly-report/status
            Method: get
        GetStatsData:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /weekly-report/stats
            Method: get
        SubmitFeedback:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /weekly-report/feedback
            Method: post

  SESFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-ses"
      CodeUri: ./src/SES
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:GetIdentityVerificationAttributes
                - ses:VerifyEmailIdentity
              Resource: "*"
      Events:
        CheckEmailApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /ses/check
            Method: ANY
        VerifyEmailApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /ses/verify
            Method: ANY

  ScheduleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-schedule"
      CodeUri: ./src/Schedule
      Policies:
        - AmazonDynamoDBFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Sub "${Stage}-send-request"
      Description: ""
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer

  SendRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-send-request"
      CodeUri: ./src/SendRequest
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
                - ses:SendEmail
              Resource: "*"
      Description: ""
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer

  SecureParameterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-secure-parameter"
      CodeUri: ./src/SecureParameter
      Environment:
        Variables:
          JWT_SECRET_PARAMETER: !Ref JwtSecretParameter
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref JwtSecretParameter
        - SecretsManagerReadWrite
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:DeleteParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/weekly-report/${Stage}/*"
      Events:
        GenerateTokenApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /secure/generate
            Method: ANY
        VerifyTokenApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /secure/verify
            Method: ANY

  # ------------------------------------------------------------#
  #  Lambda Layer
  # ------------------------------------------------------------#
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: common functions
      ContentUri: ./src/layer
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: "Delete"
    Metadata:
      BuildMethod: python3.12

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Secure Parameter API"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
