AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: infospace-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    Handler: lambda_function.lambda_handler
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        TZ: Asia/Tokyo

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsProd: !Equals [!Ref Stage, "prod"]

Resources:

# ------------------------------------------------------------#
#  Lambda Function
# ------------------------------------------------------------#
  OrganizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Stage}-organization'
      CodeUri: ./src/Organization
      Policies:
        - AmazonDynamoDBFullAccess
      Description: ''
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer
  
  MemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Stage}-member'
      CodeUri: ./src/Member
      Policies:
        - AmazonDynamoDBFullAccess
      Description: ''
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer
  
  WeeklyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Stage}-weekly-report'
      CodeUri: ./src/WeeklyReport
      Policies:
        - AmazonDynamoDBFullAccess
      Description: ''
      Environment:
        Variables:
          STAGE: !Ref Stage
      Layers:
        - !Ref CommonLayer

# ------------------------------------------------------------#
#  Lambda Layer
# ------------------------------------------------------------#
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: common functions
      ContentUri: ./src/layer
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: "Delete"
    Metadata:
      BuildMethod: python3.12
