version = 0.1
[default.deploy.parameters]
stack_name = "wrs-table"
s3_bucket = "wrs-sam-deployment-bucket"
s3_prefix = "wrs-table"
region = "ap-northeast-1"
profile = "wrs"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
