version = 0.1
[default.deploy.parameters]
stack_name = "wrs-table-prod"
s3_bucket = "wrs-sam-deployment-bucket"
s3_prefix = "wrs-table-prod"
region = "ap-northeast-1"
profile = "wrs"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
image_repositories = []
