version = 0.1
[default.deploy.parameters]
stack_name = "wrs-table-prod"
resolve_s3 = true
s3_prefix = "wrs-table-prod"
region = "ap-northeast-1"
profile = "wrs"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentName=\"prod\""
image_repositories = []
